# Site settings
name: Less Or More
email: 2047343655@qq.com
author: J.Shen
url: 
resume_site: 
github: https://github.com/gitJEffReyhub/
baseurl: ""
description: Actually, less is more!
meta_description: 沈杰;个人博客;学而不思则罔;思而不学则殆
motto: 我喜欢.
banner: hello,world.

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: gitJEffReyhub

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9


theme: jekyll-theme-time-machine