# Site settings
name: 学习
email: njuszj@qq.com
author: J.Shen
url: www.njuszj.com
resume_site: www.njuszj.com/2019/04/06/about-me/
github: https://github.com/njuszj/
baseurl: ""
description: Less is More
meta_description: 个人博客
motto:   学无止境
banner: 关山难越，谁悲失路之人；萍水相逢，尽是他乡之客。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: njuszj

# Build settings
markdown: kramdown

baidu_analysis: cfe0aa45fb635330dab1e4cd0d13fa78

